language: python

matrix:
    include:
        - python: 3.7

branches:
    only:
    - master

services:
    - docker

before_install:
  # Install the latest version of Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # For some reason miniconda installs here instead of the above path
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt
  # Install docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -


install:
  - conda install -y conda-build
  # You can add any CONDA channels you may need here. CONDA supports
  # both the commands add and append. The only difference is that
  # the add command places the channel at the front of the priority
  # list, while append does the opposite.
  - conda config --add channels conda-forge
  - conda config --add channels rdkit
  - conda config --add channels openbabel

  # Build the conda recipe for this package
  - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
  # Add the built package as a channel with highest priority
  - conda config --add channels "file://`pwd`/bld-dir"

  # Create and activate the test environment
  - conda create -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION autoenrich --file dev-requirements.txt
  - pip install -U pip

  - source activate test-environment
  - pip install -U pytest

script:
  # Run any test suite you may have
  - autoenrich -h
  - impression -h
  - ae_utils -h
  - pytest

after_success:
  # Install the command line API for CONDA uploads
  - conda install -y anaconda-client
  - export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN
  - anaconda upload bld-dir/**/autoenrich-*.tar.bz2 --label stable
  # Build and upload docker image
  - cd dockerfiles/minibox
  - docker build . -t wg12385/autoenrich:stable
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wg12385/autoenrich:stable
