package:
  name: autoenrich
  version: 1.7

source:
  git_rev: master
  git_url: https://github.com/wg12385/auto-ENRICH



requirements:
  build:
    - python
  run:
    - bayesian-optimization
    - numpy
    - python>=3.4
    - scipy
    - openbabel
    - rdkit


about:
  home: www.autoenrich.co.uk
  license: GNU Affero General Public License v3 or later (AGPLv3+)
  summary: "Computational NMR"
